<?xml version="1.0" encoding="utf-8"?><Database Name="AdventureWorks2017" Class="Form_LinqSqlConnectionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=AdventureWorks2017;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Sample3_LinqWindowsForm.Properties.Settings" SettingsPropertyName="AdventureWorks2017ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Production.Product" Member="Product">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductNumber" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="MakeFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FinishedGoodsFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SafetyStockLevel" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReorderPoint" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="StandardCost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ListPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SizeUnitMeasureCode" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="WeightUnitMeasureCode" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="DaysToManufacture" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductLine" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="ProductSubcategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductModelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SellEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiscontinuedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SAMPLE1_GET_PRODUCT_DATA" Method="SAMPLE1_GET_PRODUCT_DATA">
    <ElementType Name="SAMPLE1_GET_PRODUCT_DATAResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductNumber" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SafetyStockLevel" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReorderPoint" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ListPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SellStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAMPLE1_INSERT_PRODUCT_DATA" Method="SAMPLE1_INSERT_PRODUCT_DATA">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(512)" />
    <Parameter Name="ProductNumber" Parameter="productNumber" Type="System.String" DbType="NVarChar(512)" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="SafetyStockLevel" Parameter="safetyStockLevel" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="ReorderPoint" Parameter="reorderPoint" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="ListPrice" Parameter="listPrice" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Size" Parameter="size" Type="System.String" DbType="NVarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SAMPLE1_UPDATE_DISABLE_PRODUCT_SELLS" Method="SAMPLE1_UPDATE_DISABLE_PRODUCT_SELLS">
    <Parameter Name="ProductiD" Parameter="productiD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SAMPLE1_UPDATE_PRODUCT_PRICE" Method="SAMPLE1_UPDATE_PRODUCT_PRICE">
    <Parameter Name="ProductiD" Parameter="productiD" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListPrice" Parameter="listPrice" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SAMPLE1_DELETE_PRODUCT_SELLS" Method="SAMPLE1_DELETE_PRODUCT_SELLS">
    <Parameter Name="ProductiD" Parameter="productiD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>